# core/report.py
# Yardage card renderer: a phone-sized PNG you can save to your lock screen.

from __future__ import annotations

from io import BytesIO
from typing import List, Optional

import pandas as pd
from PIL import Image, ImageDraw, ImageFont


def _font(size: int, bold: bool = False) -> ImageFont.ImageFont:
    candidates = [
        "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "arialbd.ttf" if bold else "arial.ttf",
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
    ]
    for c in candidates:
        try:
            return ImageFont.truetype(c, size)
        except Exception:
            continue
    try:
        return ImageFont.load_default(size=size)
    except TypeError:  # older Pillow
        return ImageFont.load_default()


def render_yardage_card(card: pd.DataFrame, title: str = "My Numbers", subtitle: str = "", handedness: str = "right") -> bytes:
    """
    Render the yardage card DataFrame (from analysis.gapping.yardage_card)
    as a PNG. Columns used: Club, Safe, Plan, Max, Total, Miss, ±.
    """
    cols: List[str] = ["Club", "Safe", "Plan", "Max", "Total", "Miss", "±"]
    rows = card.to_dict(orient="records") if card is not None and not card.empty else []

    width = 900
    pad = 36
    header_h = 150
    row_h = 58
    footer_h = 90
    height = header_h + row_h * (len(rows) + 1) + footer_h

    bg = (18, 32, 24)
    panel = (26, 46, 34)
    stripe = (31, 55, 41)
    ink = (236, 240, 236)
    muted = (160, 180, 165)
    accent = (120, 220, 150)

    img = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(img)

    draw.text((pad, 30), title, font=_font(40, bold=True), fill=ink)
    sub = subtitle or "Safe = clears trouble (20th pct)   Plan = normal (median)   Max = 80th pct   ± = side spread"
    draw.text((pad, 86), sub, font=_font(19), fill=muted)

    col_x = [pad, 250, 360, 470, 580, 700, 820]
    y = header_h
    draw.rectangle([pad - 12, y, width - pad + 12, y + row_h], fill=panel)
    for x, c in zip(col_x, cols):
        draw.text((x, y + 16), c, font=_font(22, bold=True), fill=accent)
    y += row_h

    for i, r in enumerate(rows):
        if i % 2 == 0:
            draw.rectangle([pad - 12, y, width - pad + 12, y + row_h], fill=stripe)
        vals = [
            str(r.get("Club", "")),
            _fmt(r.get("Safe")),
            _fmt(r.get("Plan")),
            _fmt(r.get("Max")),
            _fmt(r.get("Total")),
            str(r.get("Miss", "-")),
            _fmt(r.get("±")),
        ]
        for j, (x, v) in enumerate(zip(col_x, vals)):
            bold = j in (0, 2)
            draw.text((x, y + 16), v, font=_font(24, bold=bold), fill=ink if j != 5 else muted)
        y += row_h

    hand = "Right-handed" if not str(handedness).lower().startswith("l") else "Left-handed"
    draw.text((pad, y + 24), f"{hand}.  Miss shows your average offline bias and direction.  Generated by Golf Coach.", font=_font(17), fill=muted)

    buf = BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def _fmt(v) -> str:
    try:
        if v is None or pd.isna(v):
            return "-"
        return f"{int(round(float(v)))}"
    except (TypeError, ValueError):
        return "-"


def render_pdf(session: dict) -> bytes:
    """Kept for compatibility: plain-text summary."""
    lines = [f"{k}: {v}" for k, v in session.items()]
    return ("\n".join(lines)).encode("utf-8")
